export const verificationStatuses = ['not_submitted','pending','verified','not_verified','more_information_required'] as const;
export type VerificationStatus = typeof verificationStatuses[number];
export const accessStatuses = ['not_available','awaiting_verification','eligible','active','paused','stopped'] as const;
export type AccessStatus = typeof accessStatuses[number];
export type StrategyAccount = { id?:string;display_name:string;deriv_account_type:string;environment:'demo'|'real';broker_entity:string;mt5_server:string;mt5_login_id:string;currency:string;country:string;funding_range:string|null;experience_range:string;referral_confirmation:'not_submitted'|'member_confirmed';affiliate_status:VerificationStatus;strategy_access_status:AccessStatus;nakala_connected:boolean;risk_acknowledged:boolean;controls_acknowledged:boolean;consent_version:string;consented_at?:string;submitted_at?:string;updated_at?:string };
export const emptyStrategyAccount:StrategyAccount={display_name:'',deriv_account_type:'MT5 Standard',environment:'real',broker_entity:'Deriv',mt5_server:'',mt5_login_id:'',currency:'USD',country:'',funding_range:null,experience_range:'beginner',referral_confirmation:'not_submitted',affiliate_status:'not_submitted',strategy_access_status:'not_available',nakala_connected:false,risk_acknowledged:false,controls_acknowledged:false,consent_version:''};
export function maskLogin(value:string){const clean=value.replace(/\s/g,'');return clean?`•••• ${clean.slice(-4).padStart(4,'•')}`:'Not submitted'}
export function validateStrategyAccount(value:StrategyAccount){const errors:string[]=[];if(!value.display_name.trim()||value.display_name.length>80)errors.push('Enter an account display name (80 characters maximum).');if(value.deriv_account_type!=='MT5 Standard')errors.push('Nakala onboarding currently requires MT5 Standard.');if(!['demo','real'].includes(value.environment))errors.push('Choose demo or real.');if(!value.mt5_server.trim()||value.mt5_server.length>100)errors.push('Enter the MT5 server shown by Deriv.');if(!/^\d{4,20}$/.test(value.mt5_login_id.trim()))errors.push('MT5 Login ID must contain 4–20 digits.');if(!/^[A-Z]{3,5}$/.test(value.currency))errors.push('Enter a valid account currency code.');if(!value.country.trim()||value.country.length>80)errors.push('Enter your country of residence.');if(value.referral_confirmation!=='member_confirmed')errors.push('Confirm whether you used the Apex partner route or need a manual check.');if(!value.risk_acknowledged||!value.controls_acknowledged)errors.push('Complete both risk and account-control acknowledgements.');return errors}
export const statusLabel=(status:string)=>({not_submitted:'Not Submitted',pending:'Verification Pending',verified:'Affiliate Referral Verified',not_verified:'Not Verified',more_information_required:'More Information Required'} as Record<string,string>)[status]||status.replace(/_/g,' ').replace(/\b\w/g,letter=>letter.toUpperCase());
