import {useEffect,useState,type FormEvent} from 'react';
import {AlertTriangle,CheckCircle,ExternalLink,Lock,Trash2} from 'lucide-react';
import {affiliateConfig} from '../config/affiliateConfig';
import {supabase} from '../lib/supabase';
import {emptyStrategyAccount,maskLogin,statusLabel,validateStrategyAccount,type StrategyAccount} from '../lib/managedStrategy';
const cfg=affiliateConfig.managedStrategy;
export function ManagedStrategy(){const [record,setRecord]=useState<StrategyAccount|null>(null),[draft,setDraft]=useState(emptyStrategyAccount),[editing,setEditing]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!cfg.enabled)return;supabase.rpc('get_own_strategy_application').then(({data,error})=>{if(error)setMessage(error.message);else if(data?.[0]){setRecord(data[0]);setDraft(data[0])}})},[]);
 const set=(k:keyof StrategyAccount,v:unknown)=>setDraft(p=>({...p,[k]:v}));
 const save=async(e:FormEvent)=>{e.preventDefault();const errors=validateStrategyAccount(draft);if(errors.length){setMessage(errors.join(' '));return}setBusy(true);const {data,error}=await supabase.rpc('upsert_own_strategy_application',{payload:{broker_entity:draft.broker_entity,mt5_server:draft.mt5_server,mt5_login_id:draft.mt5_login_id,real_account_confirmed:draft.real_account_confirmed,ownership_confirmed:draft.ownership_confirmed,risk_acknowledged:draft.risk_acknowledged,consent_version:cfg.consentVersion}});setBusy(false);if(error)setMessage(error.message);else{setRecord(data);setDraft(data);setEditing(false);setMessage('Account details submitted for administrator review.')}};
 const remove=async()=>{if(!confirm('Delete your managed-strategy account details? This cannot be undone.'))return;const {error}=await supabase.rpc('delete_own_strategy_application');if(error)setMessage(error.message);else{setRecord(null);setDraft(emptyStrategyAccount);setMessage('Account details deleted.')}};
 const verified=record?.affiliate_status==='verified';
 return <section className="managed-strategy" aria-labelledby="strategy-heading"><div className="strategy-hero"><div><p className="eyebrow">Official copy-trading onboarding</p><h2 id="strategy-heading">Apex Managed Strategy Access</h2><p>Eligible members can follow the Apex strategy through Deriv’s supported copy-trading infrastructure. You retain ownership and control of your account and may pause or stop copying at any time.</p></div><Lock/></div>
 <div className="progress-list"><span>Account created</span><span>Affiliate verification</span><span>MT5 ready</span><span>Nakala connected</span><span>Strategy active</span></div>
 {!record||editing?<form className="strategy-form" onSubmit={save}><div className="credential-warning"><AlertTriangle/><strong>Never enter your Deriv or MT5 password on this website. Account connection is completed securely through Deriv’s supported copy-trading platform.</strong></div><span className="status-pill">Real Deriv MT5 account only</span><label><span>Broker/entity name</span><input value={draft.broker_entity} onChange={e=>set('broker_entity',e.target.value)} maxLength={100} disabled={!cfg.enabled}/></label><label><span>MT5 server name</span><input value={draft.mt5_server} onChange={e=>set('mt5_server',e.target.value)} maxLength={100} disabled={!cfg.enabled}/></label><label><span>MT5 Login ID</span><input inputMode="numeric" pattern="[0-9]{4,20}" value={draft.mt5_login_id} onChange={e=>set('mt5_login_id',e.target.value.replace(/\D/g,''))} autoComplete="off" disabled={!cfg.enabled}/></label><div className="form-consents"><label><input type="checkbox" checked={draft.real_account_confirmed} onChange={e=>set('real_account_confirmed',e.target.checked)} disabled={!cfg.enabled}/> This is a compatible real Deriv MT5 Standard account.</label><label><input type="checkbox" checked={draft.ownership_confirmed} onChange={e=>set('ownership_confirmed',e.target.checked)} disabled={!cfg.enabled}/> This account belongs to me.</label><label><input type="checkbox" checked={draft.risk_acknowledged} onChange={e=>set('risk_acknowledged',e.target.checked)} disabled={!cfg.enabled}/> I acknowledge trading can result in loss, retain control of deposits and withdrawals, and may stop copying.</label></div><button className="cta cta-primary" disabled={!cfg.enabled||busy}>{busy?'Submitting…':'Submit account details'}</button>{!cfg.enabled&&<p className="fine-print">Secure submissions are not active yet. No information entered here is transmitted or stored.</p>}</form>:<div className="strategy-summary"><span className="status-pill">Real account</span><dl><div><dt>Affiliate verification</dt><dd>{statusLabel(record.affiliate_status)}</dd></div><div><dt>MT5 Login</dt><dd>{maskLogin(record.mt5_login_id)}</dd></div><div><dt>Broker/entity</dt><dd>{record.broker_entity}</dd></div><div><dt>Server</dt><dd>{record.mt5_server}</dd></div><div><dt>Strategy connection</dt><dd>{statusLabel(record.strategy_status)}</dd></div><div><dt>Submitted</dt><dd>{record.submitted_at?new Date(record.submitted_at).toLocaleDateString():'—'}</dd></div></dl><div className="strategy-actions"><button className="cta" onClick={()=>setEditing(true)}>Edit account details</button><button className="danger-button" onClick={remove}><Trash2 size={15}/> Delete account details</button></div></div>}
 {message&&<p role="status">{message}</p>}<article className={verified?'':'locked-step'}><b>Connect</b><div><h3>Connect through Deriv Nakala</h3>{verified?<><p>Open Nakala, link your compatible real Deriv MT5 Standard account, and enter any required trading password only inside Deriv’s official application. Locate the verified Apex provider, review allocation and risk controls, then activate copying.</p><a className="cta cta-secondary" href={cfg.officialSetupGuide} target="_blank" rel="noreferrer">Official Nakala instructions <ExternalLink size={15}/></a><p><strong>Provider handle:</strong> {cfg.providerHandle||'Awaiting administrator verification'}</p></>:<p>Available only after an administrator confirms the referral in Partner Hub. Existing Deriv customers should request a manual eligibility review and must not create duplicate accounts.</p>}</div></article><p className="fine-print">Apex may receive affiliate commission. Trading leveraged products involves substantial risk and may result in loss. Apex never accepts deposits or withdrawals.</p></section>}
