import { useEffect,useState,type FormEvent } from 'react';
import { AlertTriangle,CheckCircle,ExternalLink,Lock,Pencil,ShieldCheck,Trash2 } from 'lucide-react';
import { affiliateConfig } from '../config/affiliateConfig';
import { supabase } from '../lib/supabase';
import { emptyStrategyAccount,maskLogin,statusLabel,validateStrategyAccount,type StrategyAccount } from '../lib/managedStrategy';
const progress=['Account created','Affiliate verification','MT5 ready','Nakala connected','Strategy access active'];

export function ManagedStrategy(){
 const cfg=affiliateConfig.managedStrategy,[record,setRecord]=useState<StrategyAccount|null>(null),[draft,setDraft]=useState<StrategyAccount>({...emptyStrategyAccount,consent_version:cfg.consentVersion}),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(cfg.enabled)supabase.rpc('get_own_strategy_account').single().then(({data})=>{if(data){setRecord(data as StrategyAccount);setDraft(data as StrategyAccount)}})},[cfg.enabled]);
 const set=(key:keyof StrategyAccount,value:string|boolean|null)=>setDraft(old=>({...old,[key]:value}));
 const save=async(event:FormEvent)=>{event.preventDefault();const errors=validateStrategyAccount(draft);if(errors.length){setMessage(errors.join(' '));return}if(!cfg.enabled){setMessage('Secure submission is not enabled. No data was sent or stored.');return}setBusy(true);const {data,error}=await supabase.rpc('upsert_own_strategy_account',{payload:draft});setBusy(false);if(error)setMessage(error.message);else{setRecord(data as StrategyAccount);setEditing(false);setMessage('Details submitted for manual verification.')}};
 const remove=async()=>{if(!confirm('Delete your managed-strategy account-reference details? This cannot be undone.'))return;if(!cfg.enabled){setMessage('No live record exists to delete.');return}setBusy(true);const {error}=await supabase.rpc('delete_own_strategy_account');setBusy(false);if(error)setMessage(error.message);else{setRecord(null);setDraft({...emptyStrategyAccount,consent_version:cfg.consentVersion});setMessage('Account-reference details deleted.')}};
 const confirmConnection=async(connected:boolean)=>{set('nakala_connected',connected);if(!cfg.enabled){setMessage('Connection confirmation is disabled until secure onboarding is activated.');return}setBusy(true);const {data,error}=await supabase.rpc('confirm_own_nakala_connection',{connected});setBusy(false);if(error)setMessage(error.message);else{setRecord(data as StrategyAccount);setDraft(data as StrategyAccount);setMessage('Nakala connection status updated.')}};
 const step=record?.strategy_access_status==='active'?4:record?.nakala_connected?3:record?.mt5_login_id?2:record?.affiliate_status!=='not_submitted'?1:0;
 return <section className="managed-strategy" aria-labelledby="strategy-heading">
  <div className="strategy-hero"><div><p className="eyebrow">Copy-trading onboarding</p><h2 id="strategy-heading">Apex Managed Strategy Access</h2><p>Eligible members can follow the Apex trading strategy using Deriv’s supported copy-trading infrastructure. Create your account through our partner link, complete verification and connect your MT5 Standard account through Deriv Nakala. You remain in control and can pause or stop copying at any time.</p></div><ShieldCheck size={48}/></div>
  {!cfg.enabled&&<div className="feature-gate" role="status"><Lock/><div><strong>Secure submissions are not active yet</strong><p>This onboarding preview cannot save data until its database migration, administrator role and verified provider handle are configured. Do not send account details by email or chat.</p></div></div>}
  <div className="strategy-progress">{progress.map((label,index)=><div className={index<=step?'complete':''} key={label}><span>{index<step?<CheckCircle/>:index+1}</span><small>{label}</small></div>)}</div>
  {record&&<div className="account-summary"><Item label="Affiliate verification" value={statusLabel(record.affiliate_status)}/><Item label="Strategy access" value={statusLabel(record.strategy_access_status)}/><Item label="MT5 Login ID" value={maskLogin(record.mt5_login_id)}/><Item label="Account" value={`${record.deriv_account_type} · ${record.environment}`}/><Item label="Server" value={record.mt5_server}/><Item label="Submitted" value={date(record.submitted_at)}/><Item label="Last updated" value={date(record.updated_at)}/><Item label="Copy connection" value={record.nakala_connected?'Member confirmed':'Not confirmed'}/><Item label="Risk acknowledgement" value={record.risk_acknowledged?'Accepted':'Required'}/></div>}
  <div className="onboarding-steps">
   <Step n="1" title="Create your Deriv account"><p>New customers must use the Apex partner route to qualify. Deriv permits one account per person—existing customers should not create a duplicate and must request a manual eligibility check.</p><div className="strategy-actions"><a className="cta cta-primary" href={affiliateConfig.primaryAffiliateLink} target="_blank" rel="noreferrer">Create account through Apex link <ExternalLink size={15}/></a><a className="cta cta-secondary" href={affiliateConfig.learnBasicsLink.replace("/learn","/contact")}>Existing customer support</a></div></Step>
   <Step n="2" title="Verify your email and identity"><p>Complete Deriv’s required verification directly with Deriv. Apex does not collect identity documents, passwords or verification codes.</p></Step>
   <Step n="3" title="Create a real Deriv MT5 Standard account"><p>In Trader’s Hub, find MT5 Standard under CFDs, select “Get”, and follow Deriv’s on-screen steps. Nakala’s current setup guide requires a real MT5 Standard account.</p><a href={cfg.officialSetupGuide} target="_blank" rel="noreferrer" className="text-link">Official Deriv Nakala setup guide</a></Step>
   <Step n="4" title="Submit non-secret account details"><p>These references support eligibility review only and cannot be used to log in or trade.</p>{(!record||editing)&&<StrategyForm draft={draft} set={set} save={save} busy={busy} enabled={cfg.enabled}/>} {record&&!editing&&<div className="strategy-actions"><button className="cta cta-secondary" onClick={()=>setEditing(true)}><Pencil size={15}/> Edit account details</button><button className="danger-button" onClick={remove}><Trash2 size={15}/> Delete account details</button></div>}<p role="status">{message}</p></Step>
   <Step n="5" title="Affiliate verification"><p>An authorised Apex administrator checks Partner Hub separately. Email matching alone is not proof. Access stays unavailable until the account is marked “Affiliate referral verified”.</p><span className="status-pill">{statusLabel(record?.affiliate_status||'not_submitted')}</span></Step>
   <article className={record?.affiliate_status==='verified'?'':'locked-step'}><b>6</b><div><h3>Connect through Deriv Nakala</h3>{record?.affiliate_status==='verified'?<><p>Install Nakala and use your Deriv-registered email. In Account → Link Account, enter the trading password only inside Nakala, select the correct server and choose “copier”. In Discover, locate the verified Apex provider, review its terms, choose trade size/allocation and drawdown controls, then activate copying.</p><div className="strategy-actions"><a href={cfg.androidApp} target="_blank" rel="noreferrer" className="cta cta-secondary">Google Play <ExternalLink size={15}/></a><a href={cfg.iosApp} target="_blank" rel="noreferrer" className="cta cta-secondary">Apple App Store <ExternalLink size={15}/></a></div><p><strong>Provider:</strong> {cfg.providerHandle||'Awaiting verified provider handle'}</p><label className="consent-check"><input type="checkbox" checked={draft.nakala_connected} onChange={e=>confirmConnection(e.target.checked)} disabled={!cfg.enabled||busy}/> I completed connection inside Deriv Nakala.</label></>:<p><Lock size={15}/> Available after affiliate referral verification.</p>}</div></article>
  </div>
  <div className="strategy-notices"><p><strong>Affiliate notice:</strong> Apex may receive affiliate commission when an eligible account is opened through our partner link. This does not change the risk disclosure or guarantee any result.</p><p><strong>Risk notice:</strong> Trading leveraged products involves substantial risk and may result in loss. Past or simulated performance does not guarantee future results. Only trade with money you can afford to lose.</p><p><strong>Privacy and POPIA:</strong> Non-secret account references are processed only for onboarding, support and eligibility review. Apex does not accept deposits, withdrawals or investment funds. You may correct or delete your record.</p></div>
  <div className="future-module" aria-disabled="true"><Lock/><div><span>Future module · Disabled</span><h3>Direct Managed Account Access</h3><p>Unavailable unless FSCA/FSP authorisation, an approved mandate, written Deriv approval, professional compliance arrangements, approved privacy and cybersecurity controls, and country-by-country legal review are documented. Any future access must use an official delegated or broker-supported mechanism—never shared passwords.</p></div></div>
 </section>
}
function date(value?:string){return value?new Date(value).toLocaleDateString():'—'}
function Item({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Step({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <article><b>{n}</b><div><h3>{title}</h3>{children}</div></article>}
function StrategyForm({draft,set,save,busy,enabled}:{draft:StrategyAccount;set:(key:keyof StrategyAccount,value:string|boolean|null)=>void;save:(event:FormEvent)=>void;busy:boolean;enabled:boolean}){
 const field=(key:keyof StrategyAccount,label:string)=><label><span>{label}</span><input value={String(draft[key]??'')} onChange={e=>set(key,e.target.value)} required disabled={!enabled} maxLength={100}/></label>;
 return <form className="strategy-form" onSubmit={save}><div className="credential-warning"><AlertTriangle/><strong>Never submit your Deriv or MT5 password. Apex will never ask for your password, verification code or banking details.</strong></div>{field('display_name','Account display name')}{field('deriv_account_type','Deriv account type')}<label><span>Demo or real</span><select value={draft.environment} onChange={e=>set('environment',e.target.value)} disabled={!enabled}><option value="real">Real</option><option value="demo">Demo</option></select></label>{field('broker_entity','Broker/entity name')}{field('mt5_server','MT5 server name')}{field('mt5_login_id','MT5 Login ID (numbers only)')}{field('currency','Account currency')}{field('country','Country of residence')}<label><span>Approximate funding range (optional)</span><select value={draft.funding_range||''} onChange={e=>set('funding_range',e.target.value||null)} disabled={!enabled}><option value="">Prefer not to say</option><option>Under 100 USD</option><option>100–499 USD</option><option>500–1,999 USD</option><option>2,000 USD or more</option></select></label><label><span>Trading experience</span><select value={draft.experience_range} onChange={e=>set('experience_range',e.target.value)} disabled={!enabled}><option value="beginner">Under 1 year</option><option value="intermediate">1–3 years</option><option value="experienced">More than 3 years</option></select></label><label><span>Affiliate-referral confirmation</span><select value={draft.referral_confirmation} onChange={e=>set('referral_confirmation',e.target.value)} disabled={!enabled}><option value="not_submitted">Needs manual eligibility check</option><option value="member_confirmed">I used the Apex partner route</option></select></label><div className="form-consents"><label><input type="checkbox" checked={draft.risk_acknowledged} onChange={e=>set('risk_acknowledged',e.target.checked)} disabled={!enabled}/> I understand leveraged trading can result in loss and past or simulated results do not guarantee future results.</label><label><input type="checkbox" checked={draft.controls_acknowledged} onChange={e=>set('controls_acknowledged',e.target.checked)} disabled={!enabled}/> I consent to processing this non-secret reference data, control deposits and withdrawals myself, and can stop copying in Nakala.</label></div><button className="cta cta-primary" disabled={!enabled||busy}>{busy?'Submitting…':'Submit for verification'}</button>{!enabled&&<p className="fine-print">Preview only: submission is disabled and no form data is transmitted or stored.</p>}</form>
}
