import { useEffect, useRef, useState } from 'react';
import { X, Download, Upload, Trash2, Printer, Plus } from 'lucide-react';
import { calculateDrawdown, calculateTradePlan, csvToJournal, downloadText, journalStats, journalToCsv, sessionStatus, type Direction, type JournalEntry } from '../lib/memberTools';

export type PremiumTool = 'trade-planner' | 'drawdown' | 'journal' | 'sessions' | 'challenge';
const JOURNAL_KEY = 'apex-vip-journal-v1';
const CHALLENGE_KEY = 'apex-vip-demo-challenge-v1';
const checks = ['Setup identified','Risk chosen','Stop planned','Target planned','Emotional state checked','Rules followed'];

function Field(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) {
  return <label className="premium-field"><span>{props.label}</span><input {...props} /></label>;
}

export function PremiumToolModal({ tool, onClose }: { tool: PremiumTool; onClose: () => void }) {
  const panel = useRef<HTMLDivElement>(null);
  useEffect(() => { panel.current?.focus(); const listener = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); document.addEventListener('keydown', listener); return () => document.removeEventListener('keydown', listener); }, [onClose]);
  return <div className="tool-modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div ref={panel} className="tool-modal" role="dialog" aria-modal="true" aria-labelledby="tool-title" tabIndex={-1}><button className="modal-close" onClick={onClose} aria-label="Close tool"><X /></button>{tool === 'trade-planner' && <TradePlanner />}{tool === 'drawdown' && <Drawdown />}{tool === 'journal' && <Journal />}{tool === 'sessions' && <Sessions />}{tool === 'challenge' && <Challenge />}</div></div>;
}

function TradePlanner() {
  const [direction, setDirection] = useState<Direction>('buy'); const [entry, setEntry] = useState(''); const [stop, setStop] = useState(''); const [target, setTarget] = useState(''); const [size, setSize] = useState('');
  const result = calculateTradePlan(direction, entry, stop, target, size);
  return <><h2 id="tool-title">Risk-to-Reward Trade Planner</h2><p className="tool-intro">Plan a hypothetical trade before placing it. Results are estimates.</p><div className="premium-form-grid"><label className="premium-field"><span>Direction</span><select value={direction} onChange={(e) => setDirection(e.target.value as Direction)}><option value="buy">Buy</option><option value="sell">Sell</option></select></label><Field label="Entry price" type="number" min="0" step="any" value={entry} onChange={(e) => setEntry(e.target.value)} /><Field label="Stop-loss price" type="number" min="0" step="any" value={stop} onChange={(e) => setStop(e.target.value)} /><Field label="Target price" type="number" min="0" step="any" value={target} onChange={(e) => setTarget(e.target.value)} /><Field label="Position size (units)" type="number" min="0" step="any" value={size} onChange={(e) => setSize(e.target.value)} /></div>{'error' in result ? <p className="tool-hint">{result.error}</p> : <div className="result-grid" aria-live="polite"><div><span>Estimated risk</span><strong>{result.risk.toFixed(2)}</strong></div><div><span>Potential reward</span><strong>{result.reward.toFixed(2)}</strong></div><div><span>Reward:risk</span><strong>{result.ratio.toFixed(2)}:1</strong></div><div><span>Break-even price*</span><strong>{result.breakEven.toFixed(5)}</strong></div></div>}<p className="fine-print">*Before fees, spread, slippage, swaps or financing costs. This estimate does not predict execution or outcome.</p></>;
}

function Drawdown() {
  const [peak, setPeak] = useState(''); const [current, setCurrent] = useState(''); const result = calculateDrawdown(peak, current);
  return <><h2 id="tool-title">Drawdown Recovery Calculator</h2><p className="tool-intro">See why percentage losses require a larger percentage recovery.</p><div className="premium-form-grid"><Field label="Peak account balance" type="number" min="0" step="any" value={peak} onChange={(e) => setPeak(e.target.value)} /><Field label="Current balance" type="number" min="0" step="any" value={current} onChange={(e) => setCurrent(e.target.value)} /></div>{'error' in result ? <p className="tool-hint">{result.error}</p> : <><div className="progress-track" aria-label={`${result.progress.toFixed(1)} percent of peak balance remaining`}><span style={{ width: `${result.progress}%` }} /></div><div className="result-grid"><div><span>Monetary drawdown</span><strong>{result.amount.toFixed(2)}</strong></div><div><span>Drawdown</span><strong>{result.percentage.toFixed(2)}%</strong></div><div><span>Gain needed to recover</span><strong>{Number.isFinite(result.recovery) ? `${result.recovery.toFixed(2)}%` : 'Not calculable from zero'}</strong></div></div></>}<p className="fine-print">Estimates only. A recovery figure is mathematical context, not a target or recommendation.</p></>;
}

function Journal() {
  const [entries, setEntries] = useState<JournalEntry[]>(() => { try { return JSON.parse(localStorage.getItem(JOURNAL_KEY) || '[]'); } catch { return []; } });
  const [error, setError] = useState(''); const fileRef = useRef<HTMLInputElement>(null); const stats = journalStats(entries);
  useEffect(() => localStorage.setItem(JOURNAL_KEY, JSON.stringify(entries)), [entries]);
  const add = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const numeric = ['entry','exit','size','result'].map((key) => Number(data.get(key))); if (!numeric.every(Number.isFinite) || numeric[0] < 0 || numeric[1] < 0 || numeric[2] <= 0) { setError('Enter valid non-negative prices, a positive size and a numeric result.'); return; } setEntries((old) => [{ id: crypto.randomUUID(), date: String(data.get('date')), market: String(data.get('market')).trim(), account: data.get('account') as 'demo'|'live', direction: data.get('direction') as Direction, entry: numeric[0], exit: numeric[1], size: numeric[2], result: numeric[3], setup: String(data.get('setup')).trim(), notes: String(data.get('notes')).trim(), lessons: String(data.get('lessons')).trim() }, ...old]); event.currentTarget.reset(); setError(''); };
  const importCsv = async (file?: File) => { if (!file) return; try { const imported = csvToJournal(await file.text()); setEntries(imported); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not import CSV.'); } };
  return <><h2 id="tool-title">Smart Trading Journal</h2><p className="tool-intro">Entries stay in this browser unless you export them.</p><div className="journal-stats">{[['Trades',stats.total],['Win rate',`${stats.winRate.toFixed(1)}%`],['Avg win',stats.averageWin.toFixed(2)],['Avg loss',stats.averageLoss.toFixed(2)],['Net',stats.net.toFixed(2)],['Profit factor',Number.isFinite(stats.profitFactor) ? stats.profitFactor.toFixed(2) : '∞']].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><form className="journal-form" onSubmit={add}><Field name="date" label="Date" type="date" required /><Field name="market" label="Market" required maxLength={80} /><label className="premium-field"><span>Account</span><select name="account"><option value="demo">Demo</option><option value="live">Live</option></select></label><label className="premium-field"><span>Direction</span><select name="direction"><option value="buy">Buy</option><option value="sell">Sell</option></select></label><Field name="entry" label="Entry" type="number" min="0" step="any" required /><Field name="exit" label="Exit" type="number" min="0" step="any" required /><Field name="size" label="Position size" type="number" min="0" step="any" required /><Field name="result" label="Result (+/-)" type="number" step="any" required />{['setup','notes','lessons'].map((name) => <label className="premium-field premium-wide" key={name}><span>{name === 'lessons' ? 'Lessons learned' : name[0].toUpperCase()+name.slice(1)}</span><textarea name={name} maxLength={1000} /></label>)}<button className="cta" type="submit"><Plus size={16}/> Save entry</button></form>{error && <p className="tool-error" role="alert">{error}</p>}<div className="tool-actions"><button className="cta cta-secondary" onClick={() => downloadText('apex-trading-journal.csv', journalToCsv(entries), 'text/csv;charset=utf-8')} disabled={!entries.length}><Download size={16}/> Export CSV</button><button className="cta cta-secondary" onClick={() => fileRef.current?.click()}><Upload size={16}/> Import CSV</button><input ref={fileRef} className="visually-hidden" type="file" accept=".csv,text/csv" onChange={(e) => importCsv(e.target.files?.[0])} /><button className="danger-button" disabled={!entries.length} onClick={() => window.confirm('Delete all journal entries stored in this browser? This cannot be undone.') && setEntries([])}><Trash2 size={16}/> Delete all journal data</button></div><div className="journal-list">{entries.slice(0,20).map((entry) => <article key={entry.id}><strong>{entry.date} · {entry.market}</strong><span>{entry.account} · {entry.direction} · result {entry.result.toFixed(2)}</span><button aria-label={`Delete ${entry.market} entry`} onClick={() => setEntries((old) => old.filter((item) => item.id !== entry.id))}><Trash2 size={15}/></button></article>)}</div></>;
}

function Sessions() {
  const [now, setNow] = useState(new Date()); useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 60000); return () => clearInterval(timer); }, []); const status = sessionStatus(now); const open = status.filter((item) => item.isOpen).length;
  return <><h2 id="tool-title">Global Trading Session Planner</h2><p className="tool-intro">Times below are converted automatically to your timezone: <strong>{Intl.DateTimeFormat().resolvedOptions().timeZone}</strong>.</p>{open > 1 && <p className="overlap-banner">Overlap now: {status.filter((item) => item.isOpen).map((item) => item.name).join(' + ')}</p>}<div className="session-list">{status.map((session) => <article className={session.isOpen ? 'is-open' : ''} key={session.name}><div><strong>{session.name}</strong><span>{session.zone}</span></div><b>{session.localHours}</b><em>{session.isOpen ? 'Open now' : 'Closed now'}</em></article>)}</div><p className="fine-print">Session windows are conventional weekday reference hours and use IANA timezones for daylight-saving changes. Holidays, instruments and platforms vary; confirm actual market availability with your platform.</p></>;
}

type ChallengeTrade = { done: boolean; checks: boolean[]; note: string };
function Challenge() {
  const empty = () => Array.from({ length: 30 }, () => ({ done: false, checks: Array(6).fill(false), note: '' }));
  const [trades, setTrades] = useState<ChallengeTrade[]>(() => { try { const saved = JSON.parse(localStorage.getItem(CHALLENGE_KEY) || 'null'); return Array.isArray(saved) && saved.length === 30 ? saved : empty(); } catch { return empty(); } });
  useEffect(() => localStorage.setItem(CHALLENGE_KEY, JSON.stringify(trades)), [trades]); const complete = trades.filter((trade) => trade.done).length; const followed = trades.filter((trade) => trade.done).flatMap((trade) => trade.checks); const ruleRate = followed.length ? followed.filter(Boolean).length / followed.length * 100 : 0;
  const update = (index: number, next: ChallengeTrade) => setTrades((old) => old.map((trade, i) => i === index ? next : trade));
  return <><h2 id="tool-title">30-Trade Demo Practice Challenge</h2><p className="tool-intro">Build a repeatable demo routine. Completion is about following a process—not proving profitability.</p><div className="challenge-summary"><strong>{complete}/30 practice trades</strong><span>{ruleRate.toFixed(0)}% checklist completion</span></div><div className="progress-track"><span style={{ width: `${complete / 30 * 100}%` }} /></div><div className="challenge-list">{trades.map((trade,index) => <details key={index} open={index === complete}><summary><span>Practice trade {index + 1}</span><b>{trade.done ? 'Complete' : 'Not complete'}</b></summary><div className="check-grid">{checks.map((label, checkIndex) => <label key={label}><input type="checkbox" checked={trade.checks[checkIndex]} onChange={(e) => update(index,{...trade,checks:trade.checks.map((value,i)=>i===checkIndex?e.target.checked:value)})}/>{label}</label>)}</div><label className="premium-field"><span>Practice note</span><textarea maxLength={500} value={trade.note} onChange={(e) => update(index,{...trade,note:e.target.value})}/></label><label className="complete-check"><input type="checkbox" checked={trade.done} onChange={(e)=>update(index,{...trade,done:e.target.checked})}/> Mark this demo trade complete</label></details>)}</div><div className="tool-actions"><button className="cta cta-secondary" onClick={() => window.print()}><Printer size={16}/> Printable summary</button><button className="danger-button" onClick={() => window.confirm('Reset all 30 demo-practice entries? This cannot be undone.') && setTrades(empty())}><Trash2 size={16}/> Reset challenge</button></div><p className="fine-print">Demo results do not predict live results. Trading involves risk; keep using written limits and independent judgment.</p></>;
}
