-- Real-account-only managed strategy model. Never store trading credentials.
create table if not exists public.member_profiles(user_id uuid primary key references auth.users(id) on delete cascade,display_name text check(char_length(display_name)<=100),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.mt5_account_references(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,broker_entity text not null check(char_length(trim(broker_entity)) between 1 and 100),mt5_server text not null check(char_length(trim(mt5_server)) between 1 and 100),mt5_login_id text not null check(mt5_login_id ~ '^[0-9]{4,20}$'),real_account_confirmed boolean not null check(real_account_confirmed),ownership_confirmed boolean not null check(ownership_confirmed),submitted_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.affiliate_verifications(user_id uuid primary key references auth.users(id) on delete cascade,status text not null default 'pending' check(status in('pending','verified','not_verified')),reviewed_by uuid references auth.users(id),reviewed_at timestamptz,updated_at timestamptz not null default now());
create table public.strategy_connections(user_id uuid primary key references auth.users(id) on delete cascade,status text not null default 'strategy_connection_pending' check(status in('mt5_account_ready','strategy_connection_pending','strategy_active')),nakala_status text not null default 'not_connected' check(nakala_status in('not_connected','connected')),connected_at timestamptz,provider_handle text not null default '' check(char_length(provider_handle)<=100),copying_active boolean not null default false,updated_at timestamptz not null default now());
create table public.risk_acknowledgements(user_id uuid primary key references auth.users(id) on delete cascade,accepted boolean not null check(accepted),consent_version text not null,accepted_at timestamptz not null default now());
create table public.strategy_admin_audit(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id),actor_id uuid not null references auth.users(id),action text not null,old_status text,new_status text,detail jsonb not null default '{}',created_at timestamptz not null default now());

alter table public.member_profiles enable row level security;alter table public.mt5_account_references enable row level security;alter table public.affiliate_verifications enable row level security;alter table public.strategy_connections enable row level security;alter table public.risk_acknowledgements enable row level security;alter table public.strategy_admin_audit enable row level security;
create policy profile_own_select on public.member_profiles for select to authenticated using(user_id=auth.uid());create policy profile_own_update on public.member_profiles for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy mt5_own_select on public.mt5_account_references for select to authenticated using(user_id=auth.uid());create policy affiliate_own_select on public.affiliate_verifications for select to authenticated using(user_id=auth.uid());create policy connection_own_select on public.strategy_connections for select to authenticated using(user_id=auth.uid());create policy risk_own_select on public.risk_acknowledgements for select to authenticated using(user_id=auth.uid());
create policy admin_mt5_select on public.mt5_account_references for select to authenticated using(public.is_strategy_admin());create policy admin_affiliate_select on public.affiliate_verifications for select to authenticated using(public.is_strategy_admin());create policy admin_connection_select on public.strategy_connections for select to authenticated using(public.is_strategy_admin());create policy admin_risk_select on public.risk_acknowledgements for select to authenticated using(public.is_strategy_admin());create policy admin_audit_select on public.strategy_admin_audit for select to authenticated using(public.is_strategy_admin());
revoke insert,update,delete on public.mt5_account_references,public.affiliate_verifications,public.strategy_connections,public.risk_acknowledgements,public.strategy_admin_audit from anon,authenticated;
grant select on public.member_profiles,public.mt5_account_references,public.affiliate_verifications,public.strategy_connections,public.risk_acknowledgements,public.strategy_admin_audit to authenticated;

create or replace function public.get_own_strategy_application() returns table(id uuid,broker_entity text,mt5_server text,mt5_login_id text,real_account_confirmed boolean,ownership_confirmed boolean,risk_acknowledged boolean,affiliate_status text,strategy_status text,nakala_status text,connected_at timestamptz,provider_handle text,copying_active boolean,submitted_at timestamptz,updated_at timestamptz) language sql stable security definer set search_path='' as $$ select m.id,m.broker_entity,m.mt5_server,m.mt5_login_id,m.real_account_confirmed,m.ownership_confirmed,coalesce(r.accepted,false),coalesce(a.status,'pending'),coalesce(s.status,'affiliate_verification_pending'),coalesce(s.nakala_status,'not_connected'),s.connected_at,coalesce(s.provider_handle,''),coalesce(s.copying_active,false),m.submitted_at,greatest(m.updated_at,coalesce(a.updated_at,m.updated_at),coalesce(s.updated_at,m.updated_at)) from public.mt5_account_references m left join public.risk_acknowledgements r using(user_id) left join public.affiliate_verifications a using(user_id) left join public.strategy_connections s using(user_id) where m.user_id=auth.uid() $$;
create or replace function public.upsert_own_strategy_application(payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null then raise exception 'Authentication required';end if;if payload ?| array['password','mt5_password','investor_password','api_token','auth_code','recovery_code','banking_details'] then raise exception 'Credential fields are prohibited';end if;if coalesce((payload->>'real_account_confirmed')::boolean,false) is not true then raise exception 'Only real Deriv MT5 accounts are accepted';end if;if coalesce((payload->>'ownership_confirmed')::boolean,false) is not true or coalesce((payload->>'risk_acknowledged')::boolean,false) is not true then raise exception 'Required confirmations are missing';end if;if coalesce(payload->>'mt5_login_id','') !~ '^[0-9]{4,20}$' then raise exception 'Invalid MT5 Login ID';end if;insert into public.mt5_account_references(user_id,broker_entity,mt5_server,mt5_login_id,real_account_confirmed,ownership_confirmed) values(auth.uid(),trim(payload->>'broker_entity'),trim(payload->>'mt5_server'),payload->>'mt5_login_id',true,true) on conflict(user_id) do update set broker_entity=excluded.broker_entity,mt5_server=excluded.mt5_server,mt5_login_id=excluded.mt5_login_id,updated_at=now();insert into public.risk_acknowledgements(user_id,accepted,consent_version) values(auth.uid(),true,left(payload->>'consent_version',80)) on conflict(user_id) do update set accepted=true,consent_version=excluded.consent_version,accepted_at=now();insert into public.affiliate_verifications(user_id) values(auth.uid()) on conflict do nothing;return (select to_jsonb(x) from public.get_own_strategy_application() x limit 1);end $$;
create or replace function public.delete_own_strategy_application() returns void language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null then raise exception 'Authentication required';end if;delete from public.mt5_account_references where user_id=auth.uid();delete from public.risk_acknowledgements where user_id=auth.uid();delete from public.affiliate_verifications where user_id=auth.uid();delete from public.strategy_connections where user_id=auth.uid();end $$;
create or replace function public.admin_set_strategy_status(member uuid,affiliate text,strategy text,detail text default '') returns void language plpgsql security definer set search_path='' as $$ declare old text;begin if not public.is_strategy_admin() then raise exception 'Administrator role required';end if;if affiliate not in('pending','verified','not_verified') then raise exception 'Invalid affiliate status';end if;if strategy not in('affiliate_verification_pending','affiliate_verified','affiliate_not_verified','mt5_account_ready','strategy_connection_pending','strategy_active') then raise exception 'Invalid strategy status';end if;if strategy in('affiliate_verified','mt5_account_ready','strategy_connection_pending','strategy_active') and affiliate<>'verified' then raise exception 'Affiliate verification required';end if;select status into old from public.affiliate_verifications where user_id=member for update;update public.affiliate_verifications set status=affiliate,reviewed_by=auth.uid(),reviewed_at=now(),updated_at=now() where user_id=member;insert into public.strategy_connections(user_id,status) values(member,strategy) on conflict(user_id) do update set status=excluded.status,updated_at=now();insert into public.strategy_admin_audit(user_id,actor_id,action,old_status,new_status,detail) values(member,auth.uid(),'admin_status_change',old,affiliate,jsonb_build_object('reason',left(detail,500)));end $$;
revoke all on function public.get_own_strategy_application(),public.upsert_own_strategy_application(jsonb),public.delete_own_strategy_application(),public.admin_set_strategy_status(uuid,text,text,text) from public,anon;grant execute on function public.get_own_strategy_application(),public.upsert_own_strategy_application(jsonb),public.delete_own_strategy_application(),public.admin_set_strategy_status(uuid,text,text,text) to authenticated;
comment on table public.mt5_account_references is 'Non-secret real Deriv MT5 account references only. Never store passwords.';
create or replace function public.admin_list_strategy_applications(query text default '') returns table(user_id uuid,member_email text,broker_entity text,mt5_server text,masked_mt5_login text,affiliate_status text,strategy_status text,risk_acknowledged boolean,submitted_at timestamptz,updated_at timestamptz) language sql stable security definer set search_path='' as $$ select m.user_id,u.email,m.broker_entity,m.mt5_server,'•••• '||right(m.mt5_login_id,4),a.status,coalesce(s.status,'affiliate_verification_pending'),coalesce(r.accepted,false),m.submitted_at,greatest(m.updated_at,a.updated_at,coalesce(s.updated_at,m.updated_at)) from public.mt5_account_references m join auth.users u on u.id=m.user_id join public.affiliate_verifications a using(user_id) left join public.strategy_connections s using(user_id) left join public.risk_acknowledgements r using(user_id) where public.is_strategy_admin() and (coalesce(query,'')='' or u.email ilike '%'||left(query,100)||'%' or m.broker_entity ilike '%'||left(query,100)||'%' or m.mt5_server ilike '%'||left(query,100)||'%') order by m.updated_at desc limit 200 $$;
revoke all on function public.admin_list_strategy_applications(text) from public,anon;grant execute on function public.admin_list_strategy_applications(text) to authenticated;
